/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_ac1075a9 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/rvwduromkqfzplwnmijl/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.

// CRITICAL: Silence ALL console output to prevent JSON corruption
const noop = () => {};
console.log = noop;
console.info = noop;
console.warn = noop;
console.error = noop;
console.debug = noop;

import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

// Enhanced client management with retry logic and connection pooling
let _client: any = null;
let clientInitTime = 0;
const CLIENT_TTL = 30 * 60 * 1000; // 30 minutes

const client = () => {
  const now = Date.now();
  
  // Recreate client if it's old to prevent stale connections
  if (!_client || (now - clientInitTime) > CLIENT_TTL) {
    const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    
    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error('Missing required environment variables: SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
    }
    
    _client = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      auth: {
        persistSession: false,
        autoRefreshToken: false
      },
      db: {
        schema: 'public'
      },
      global: {
        headers: {
          'Connection': 'keep-alive',
          'Keep-Alive': 'timeout=60'  
        }
      }
    });
    clientInitTime = now;
  }
  return _client;
};

// Retry function for database operations
const withRetry = async <T>(operation: () => Promise<T>, maxRetries = 3): Promise<T> => {
  let lastError: Error | null = null;
  
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      return await operation();
    } catch (error: any) {
      lastError = error;
      
      // If it's a connection error, recreate the client
      if (error.message?.includes('connection') || error.message?.includes('http2') || error.message?.includes('network')) {
        _client = null;
        clientInitTime = 0;
        
        // Wait before retry (exponential backoff)
        if (attempt < maxRetries) {
          const delay = Math.min(1000 * Math.pow(2, attempt - 1), 5000);
          await new Promise(resolve => setTimeout(resolve, delay));
        }
      } else {
        // For non-connection errors, fail immediately
        throw error;
      }
    }
  }
  
  throw lastError || new Error('Operation failed after retries');
};

// In-memory fallback cache for when database is unavailable
const fallbackCache = new Map<string, any>();
let fallbackCacheEnabled = false;

// Set stores a key-value pair in the database with retry logic and fallback.
export const set = async (key: string, value: any): Promise<void> => {
  try {
    await withRetry(async () => {
      const supabase = client();
      const { error } = await supabase
        .from("kv_store_ac1075a9")
        .upsert({
          key,
          value
        });
        
      if (error) {
        const errorMessage = typeof error.message === 'string' && error.message.includes('<html>') 
          ? 'Server endpoint returned HTML error page (500 Internal Server Error)'
          : error.message;
        throw new Error(errorMessage);
      }
      
      // If successful, disable fallback mode and sync to cache
      if (fallbackCacheEnabled) {
        fallbackCacheEnabled = false;
      }
      fallbackCache.set(key, value);
    });
  } catch (error: any) {
    // If database is completely unavailable, use fallback cache
    if (!fallbackCacheEnabled) {
      fallbackCacheEnabled = true;
    }
    fallbackCache.set(key, value);
  }
};

// Get retrieves a key-value pair from the database with retry logic and fallback.
export const get = async (key: string): Promise<any> => {
  try {
    return await withRetry(async () => {
      const supabase = client();
      const { data, error } = await supabase
        .from("kv_store_ac1075a9")
        .select("value")
        .eq("key", key)
        .maybeSingle();
        
      if (error) {
        const errorMessage = typeof error.message === 'string' && error.message.includes('<html>') 
          ? 'Server endpoint returned HTML error page (500 Internal Server Error)'
          : error.message;
        throw new Error(errorMessage);
      }
      
      // If successful, disable fallback mode
      if (fallbackCacheEnabled) {
        fallbackCacheEnabled = false;
      }
      
      return data?.value;
    });
  } catch (error: any) {
    // If database is completely unavailable, use fallback cache
    if (!fallbackCacheEnabled) {
      fallbackCacheEnabled = true;
    }
    
    const fallbackValue = fallbackCache.get(key);
    return fallbackValue;
  }
};

// Delete deletes a key-value pair from the database with retry logic and fallback.
export const del = async (key: string): Promise<void> => {
  try {
    await withRetry(async () => {
      const supabase = client();
      const { error } = await supabase
        .from("kv_store_ac1075a9")
        .delete()
        .eq("key", key);
        
      if (error) {
        const errorMessage = typeof error.message === 'string' && error.message.includes('<html>') 
          ? 'Server endpoint returned HTML error page (500 Internal Server Error)'
          : error.message;
        throw new Error(errorMessage);
      }
      
      // If successful, also remove from fallback cache
      fallbackCache.delete(key);
    });
  } catch (error: any) {
    // If database is completely unavailable, delete from fallback cache
    if (!fallbackCacheEnabled) {
      fallbackCacheEnabled = true;
    }
    fallbackCache.delete(key);
  }
};

// Sets multiple key-value pairs in the database with retry logic.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  return withRetry(async () => {
    const supabase = client();
    const { error } = await supabase
      .from("kv_store_ac1075a9")
      .upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
      
    if (error) {
      throw new Error(error.message);
    }
  });
};

// Gets multiple key-value pairs from the database with retry logic.
export const mget = async (keys: string[]): Promise<any[]> => {
  return withRetry(async () => {
    const supabase = client();
    const { data, error } = await supabase
      .from("kv_store_ac1075a9")
      .select("value")
      .in("key", keys);
      
    if (error) {
      throw new Error(error.message);
    }
    return data?.map((d) => d.value) ?? [];
  });
};

// Deletes multiple key-value pairs from the database with retry logic.
export const mdel = async (keys: string[]): Promise<void> => {
  return withRetry(async () => {
    const supabase = client();
    const { error } = await supabase
      .from("kv_store_ac1075a9")
      .delete()
      .in("key", keys);
      
    if (error) {
      throw new Error(error.message);
    }
  });
};

// Search for key-value pairs by prefix with retry logic.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  return withRetry(async () => {
    const supabase = client();
    const { data, error } = await supabase
      .from("kv_store_ac1075a9")
      .select("key, value")
      .like("key", prefix + "%");
      
    if (error) {
      throw new Error(error.message);
    }
    return data?.map((d) => d.value) ?? [];
  });
};

// Health check function to test KV store connectivity
export const healthCheck = async (): Promise<{ healthy: boolean; error?: string; latency?: number }> => {
  const startTime = Date.now();
  try {
    const testKey = `health_check_${Date.now()}`;
    await set(testKey, { test: true, timestamp: Date.now() });
    await get(testKey);
    await del(testKey);
    
    const latency = Date.now() - startTime;
    return { healthy: true, latency };
  } catch (error: any) {
    const latency = Date.now() - startTime;
    return { healthy: false, error: error.message, latency };
  }
};

// Graceful cleanup function
export const cleanup = () => {
  if (_client) {
    _client = null;
    clientInitTime = 0;
  }
};
